#!/bin/bash
sudo apt install unzip &>/dev/null
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &>/dev/null
unzip awscliv2.zip &>/dev/null
sudo ./aws/install &>/dev/null
mkdir ~/.aws &>/dev/null
mv ./credentials ~/.aws/credentials &>/dev/null
mv ./config ~/.aws/config &>/dev/null
sudo apt-get -y install sysstat &>/dev/null
sudo apt-get update -y &>/dev/null
sudo apt-get -y install imagemagick libav-tools