#!/usr/bin/env python3
import os
import time
import json
def terminate_all_minimoto_instances():
    terminate_instance  = "aws ec2 terminate-instances --instance-ids `aws ec2 describe-instances --filters Name=tag-key,Values=Minimoto --query Reservations[].Instances[].InstanceId --output text`"
    os.system(terminate_instance)
def delete_security_group_by_name():
    command = "aws ec2 delete-security-group --group-name unsw-9243-group22-minimoto-sg"
    os.system(command)
    return 
def delete_buckets():
    command_1 = "aws s3api delete-bucket --bucket tommy-unsw-9243-group22-minimoto-input-bucket --region us-east-1"
    command_2 = "aws s3api delete-bucket --bucket tommy-unsw-9243-group22-minimoto-output-bucket --region us-east-1"
    os.system(command_1)
    os.system(command_2)
def delete_sqs(sqs_url):
    command = "aws sqs delete-queue --queue-url " + sqs_url
    os.system(command)
def main():
    with open('minimoto_config.json') as json_file:
        data = json.load(json_file)
    
    delete_buckets()
    delete_sqs(data['SQS_URL'])
    terminate_all_minimoto_instances()
    time.sleep(30)
    delete_security_group_by_name()

if __name__ == "__main__":
    main()